services:
  postgres:
    image: postgis/postgis:16-3.4-alpine
    environment:
      POSTGRES_DB: rakt_food_app
      POSTGRES_USER: rakt_food_app
      POSTGRES_PASSWORD: rakt_food_app
    ports:
      - "5432:5432"
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver
