# Generated by Django 5.1.1 on 2024-09-09 17:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('facility_type', models.CharField(max_length=50)),
                ('cnn', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('block_lot', models.CharField(max_length=20)),
                ('block', models.CharField(max_length=20)),
                ('lot', models.CharField(max_length=20)),
                ('permit', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('REQUESTED', 'Requested'), ('SUSPEND', 'Pending'), ('EXPIRED', 'Expired'), ('ISSUED', 'Issued')], max_length=20)),
                ('food_items', models.CharField(max_length=100)),
                ('x_coordinate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('y_coordinate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('schedule', models.URLField()),
                ('days_hours', models.CharField(max_length=100)),
                ('approved_date', models.DateField()),
                ('received_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('prior_permit', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('location_id', models.BigIntegerField()),
                ('fire_prevention_district', models.CharField(max_length=6)),
                ('police_district', models.CharField(max_length=6)),
                ('supervisor_district', models.CharField(max_length=6)),
                ('zip_code', models.CharField(max_length=20)),
                ('neighborhood', models.CharField(max_length=6)),
            ],
        ),
    ]
