# Generated by Django 5.1.1 on 2024-09-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_trucks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='location_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
