# Generated by Django 5.1.1 on 2024-09-10 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_trucks', '0002_alter_foodtruck_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='x_coordinate',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='y_coordinate',
            field=models.DecimalField(decimal_places=15, max_digits=20),
        ),
    ]
