# Generated by Django 5.1.1 on 2024-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_trucks', '0007_alter_foodtruck_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='food_items',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='foodtruck',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
