# Generated by Django 5.1.1 on 2024-09-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_trucks', '0008_alter_foodtruck_address_alter_foodtruck_food_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='address',
            field=models.CharField(max_length=300),
        ),
    ]
