# Generated by Django 5.1.1 on 2024-09-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_trucks', '0010_alter_foodtruck_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='schedule',
            field=models.URLField(max_length=500),
        ),
    ]
