# Generated by Django 5.1.1 on 2024-09-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_trucks', '0015_alter_foodtruck_received_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodtruck',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
